# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "standalone" do |standalone|
    standalone.vm.hostname = "standalone"
    standalone.vm.network "forwarded_port", host: 3306, guest: 3306, id: "mysql"

    standalone.vm.provision :puppet do |puppet|
      puppet.module_path = "modules"
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "standalone.pp"
    end
  end

end
