# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos64min"

  config.vm.define "standalone" do |standalone|
    standalone.vm.hostname = "standalone"
    standalone.vm.network "forwarded_port", host: 8080, guest: 8080, id: "tomcat_01"
    standalone.vm.network "forwarded_port", host: 8081, guest: 8081, id: "tomcat_02"

    standalone.vm.provision :puppet do |puppet|
      puppet.module_path = "modules"
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "standalone.pp"
    end
  end
end
